ROLES = {
	NONE = 0,
	SURVIVOR = 1,
	KNIGHT = 2
}

MATCH_STATES = {
	WARM_UP = 1,
	WAITING_PLAYERS = 2,
	IN_PROGRESS = 3,
	POST_TIME = 4,
	PREPARING = 5,
}

KNIGHT_ARCHETYPES = {}

function ADD_KNIGHT_ARCHETYPE(archetype)
	archetype.id = #KNIGHT_ARCHETYPES + 1
	table.insert(KNIGHT_ARCHETYPES, archetype)
end